import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config({ path: ".env" });

const connection = await mysql.createConnection(process.env.DATABASE_URL);
const db = drizzle(connection);

// Seed suburbs in batches
const suburbs = [
  { name: "Melbourne CBD", postcode: "3000", lga: "Melbourne", zone: "inner" },
  { name: "Southbank", postcode: "3006", lga: "Melbourne", zone: "inner" },
  { name: "Docklands", postcode: "3008", lga: "Melbourne", zone: "inner" },
  { name: "Carlton", postcode: "3053", lga: "Melbourne", zone: "inner" },
  { name: "Fitzroy", postcode: "3065", lga: "Yarra", zone: "inner" },
  { name: "Collingwood", postcode: "3066", lga: "Yarra", zone: "inner" },
  { name: "Richmond", postcode: "3121", lga: "Yarra", zone: "inner" },
  { name: "South Yarra", postcode: "3141", lga: "Stonnington", zone: "inner" },
  { name: "Prahran", postcode: "3181", lga: "Stonnington", zone: "inner" },
  { name: "Windsor", postcode: "3181", lga: "Stonnington", zone: "inner" },
  { name: "St Kilda", postcode: "3182", lga: "Port Phillip", zone: "inner" },
  { name: "Elwood", postcode: "3184", lga: "Port Phillip", zone: "inner" },
  { name: "Port Melbourne", postcode: "3207", lga: "Port Phillip", zone: "inner" },
  { name: "Albert Park", postcode: "3206", lga: "Port Phillip", zone: "inner" },
  { name: "South Melbourne", postcode: "3205", lga: "Port Phillip", zone: "inner" },
  { name: "North Melbourne", postcode: "3051", lga: "Melbourne", zone: "inner" },
  { name: "West Melbourne", postcode: "3003", lga: "Melbourne", zone: "inner" },
  { name: "Kensington", postcode: "3031", lga: "Melbourne", zone: "inner" },
  { name: "Flemington", postcode: "3031", lga: "Melbourne", zone: "inner" },
  { name: "Brunswick", postcode: "3056", lga: "Moreland", zone: "inner" },
  { name: "Brunswick East", postcode: "3057", lga: "Moreland", zone: "inner" },
  { name: "Brunswick West", postcode: "3055", lga: "Moreland", zone: "inner" },
  { name: "Coburg", postcode: "3058", lga: "Moreland", zone: "inner" },
  { name: "Northcote", postcode: "3070", lga: "Darebin", zone: "inner" },
  { name: "Thornbury", postcode: "3071", lga: "Darebin", zone: "inner" },
  { name: "Preston", postcode: "3072", lga: "Darebin", zone: "inner" },
  { name: "Reservoir", postcode: "3073", lga: "Darebin", zone: "inner" },
  { name: "Hawthorn", postcode: "3122", lga: "Boroondara", zone: "inner" },
  { name: "Hawthorn East", postcode: "3123", lga: "Boroondara", zone: "inner" },
  { name: "Camberwell", postcode: "3124", lga: "Boroondara", zone: "inner" },
  { name: "Glen Iris", postcode: "3146", lga: "Boroondara", zone: "inner" },
  { name: "Malvern", postcode: "3144", lga: "Stonnington", zone: "inner" },
  { name: "Malvern East", postcode: "3145", lga: "Stonnington", zone: "inner" },
  { name: "Armadale", postcode: "3143", lga: "Stonnington", zone: "inner" },
  { name: "Toorak", postcode: "3142", lga: "Stonnington", zone: "inner" },
  { name: "Caulfield", postcode: "3162", lga: "Glen Eira", zone: "inner" },
  { name: "Caulfield North", postcode: "3161", lga: "Glen Eira", zone: "inner" },
  { name: "St Kilda East", postcode: "3183", lga: "Glen Eira", zone: "inner" },
  { name: "Balaclava", postcode: "3183", lga: "Port Phillip", zone: "inner" },
  { name: "Abbotsford", postcode: "3067", lga: "Yarra", zone: "inner" },
  { name: "Clifton Hill", postcode: "3068", lga: "Yarra", zone: "inner" },
  { name: "Parkville", postcode: "3052", lga: "Melbourne", zone: "inner" },
  { name: "East Melbourne", postcode: "3002", lga: "Melbourne", zone: "inner" },
  { name: "Ascot Vale", postcode: "3032", lga: "Moonee Valley", zone: "inner" },
  { name: "Moonee Ponds", postcode: "3039", lga: "Moonee Valley", zone: "inner" },
  { name: "Footscray", postcode: "3011", lga: "Maribyrnong", zone: "inner" },
  { name: "Yarraville", postcode: "3013", lga: "Maribyrnong", zone: "inner" },
  { name: "Seddon", postcode: "3011", lga: "Maribyrnong", zone: "inner" },
  { name: "Williamstown", postcode: "3016", lga: "Hobsons Bay", zone: "inner" },
  { name: "Newport", postcode: "3015", lga: "Hobsons Bay", zone: "inner" },
  { name: "Kew", postcode: "3101", lga: "Boroondara", zone: "inner" },
  { name: "Kew East", postcode: "3102", lga: "Boroondara", zone: "inner" },
  { name: "Alphington", postcode: "3078", lga: "Darebin", zone: "inner" },
  { name: "Fairfield", postcode: "3078", lga: "Darebin", zone: "inner" },
  { name: "Fitzroy North", postcode: "3068", lga: "Yarra", zone: "inner" },
  { name: "Burnley", postcode: "3121", lga: "Yarra", zone: "inner" },
  { name: "Cremorne", postcode: "3121", lga: "Yarra", zone: "inner" },
  { name: "Elsternwick", postcode: "3185", lga: "Glen Eira", zone: "inner" },
  { name: "Essendon", postcode: "3040", lga: "Moonee Valley", zone: "middle" },
  { name: "Essendon North", postcode: "3041", lga: "Moonee Valley", zone: "middle" },
  { name: "Altona", postcode: "3018", lga: "Hobsons Bay", zone: "middle" },
  { name: "Altona North", postcode: "3025", lga: "Hobsons Bay", zone: "middle" },
  { name: "Sunshine", postcode: "3020", lga: "Brimbank", zone: "middle" },
  { name: "St Albans", postcode: "3021", lga: "Brimbank", zone: "middle" },
  { name: "Deer Park", postcode: "3023", lga: "Brimbank", zone: "middle" },
  { name: "Keilor East", postcode: "3033", lga: "Brimbank", zone: "middle" },
  { name: "Broadmeadows", postcode: "3047", lga: "Hume", zone: "middle" },
  { name: "Tullamarine", postcode: "3043", lga: "Hume", zone: "middle" },
  { name: "Gladstone Park", postcode: "3043", lga: "Hume", zone: "middle" },
  { name: "Glenroy", postcode: "3046", lga: "Moreland", zone: "middle" },
  { name: "Pascoe Vale", postcode: "3044", lga: "Moreland", zone: "middle" },
  { name: "Fawkner", postcode: "3060", lga: "Moreland", zone: "middle" },
  { name: "Lalor", postcode: "3075", lga: "Whittlesea", zone: "middle" },
  { name: "Thomastown", postcode: "3074", lga: "Whittlesea", zone: "middle" },
  { name: "Bundoora", postcode: "3083", lga: "Banyule", zone: "middle" },
  { name: "Greensborough", postcode: "3088", lga: "Banyule", zone: "middle" },
  { name: "Heidelberg", postcode: "3084", lga: "Banyule", zone: "middle" },
  { name: "Ivanhoe", postcode: "3079", lga: "Banyule", zone: "middle" },
  { name: "Templestowe", postcode: "3106", lga: "Manningham", zone: "middle" },
  { name: "Doncaster", postcode: "3108", lga: "Manningham", zone: "middle" },
  { name: "Doncaster East", postcode: "3109", lga: "Manningham", zone: "middle" },
  { name: "Glen Waverley", postcode: "3150", lga: "Monash", zone: "middle" },
  { name: "Mount Waverley", postcode: "3149", lga: "Monash", zone: "middle" },
  { name: "Oakleigh", postcode: "3166", lga: "Monash", zone: "middle" },
  { name: "Clayton", postcode: "3168", lga: "Monash", zone: "middle" },
  { name: "Springvale", postcode: "3171", lga: "Greater Dandenong", zone: "middle" },
  { name: "Noble Park", postcode: "3174", lga: "Greater Dandenong", zone: "middle" },
  { name: "Sandringham", postcode: "3191", lga: "Bayside", zone: "middle" },
  { name: "Hampton", postcode: "3188", lga: "Bayside", zone: "middle" },
  { name: "Brighton", postcode: "3186", lga: "Bayside", zone: "middle" },
  { name: "Brighton East", postcode: "3187", lga: "Bayside", zone: "middle" },
  { name: "Beaumaris", postcode: "3193", lga: "Bayside", zone: "middle" },
  { name: "Cheltenham", postcode: "3192", lga: "Kingston", zone: "middle" },
  { name: "Mentone", postcode: "3194", lga: "Kingston", zone: "middle" },
  { name: "Parkdale", postcode: "3195", lga: "Kingston", zone: "middle" },
  { name: "Mordialloc", postcode: "3195", lga: "Kingston", zone: "middle" },
  { name: "Bentleigh", postcode: "3204", lga: "Glen Eira", zone: "middle" },
  { name: "Bentleigh East", postcode: "3165", lga: "Glen Eira", zone: "middle" },
  { name: "Carnegie", postcode: "3163", lga: "Glen Eira", zone: "middle" },
  { name: "Box Hill", postcode: "3128", lga: "Whitehorse", zone: "middle" },
  { name: "Blackburn", postcode: "3130", lga: "Whitehorse", zone: "middle" },
  { name: "Nunawading", postcode: "3131", lga: "Whitehorse", zone: "middle" },
  { name: "Mitcham", postcode: "3132", lga: "Whitehorse", zone: "middle" },
  { name: "Vermont", postcode: "3133", lga: "Whitehorse", zone: "middle" },
  { name: "Surrey Hills", postcode: "3127", lga: "Boroondara", zone: "middle" },
  { name: "Balwyn", postcode: "3103", lga: "Boroondara", zone: "middle" },
  { name: "Balwyn North", postcode: "3104", lga: "Boroondara", zone: "middle" },
  { name: "Craigieburn", postcode: "3064", lga: "Hume", zone: "outer" },
  { name: "Roxburgh Park", postcode: "3064", lga: "Hume", zone: "outer" },
  { name: "Epping", postcode: "3076", lga: "Whittlesea", zone: "outer" },
  { name: "South Morang", postcode: "3752", lga: "Whittlesea", zone: "outer" },
  { name: "Mill Park", postcode: "3082", lga: "Whittlesea", zone: "outer" },
  { name: "Doreen", postcode: "3754", lga: "Whittlesea", zone: "outer" },
  { name: "Mernda", postcode: "3754", lga: "Whittlesea", zone: "outer" },
  { name: "Wollert", postcode: "3750", lga: "Whittlesea", zone: "outer" },
  { name: "Eltham", postcode: "3095", lga: "Nillumbik", zone: "outer" },
  { name: "Diamond Creek", postcode: "3089", lga: "Nillumbik", zone: "outer" },
  { name: "Ringwood", postcode: "3134", lga: "Maroondah", zone: "outer" },
  { name: "Croydon", postcode: "3136", lga: "Maroondah", zone: "outer" },
  { name: "Bayswater", postcode: "3153", lga: "Knox", zone: "outer" },
  { name: "Boronia", postcode: "3155", lga: "Knox", zone: "outer" },
  { name: "Wantirna", postcode: "3152", lga: "Knox", zone: "outer" },
  { name: "Ferntree Gully", postcode: "3156", lga: "Knox", zone: "outer" },
  { name: "Rowville", postcode: "3178", lga: "Knox", zone: "outer" },
  { name: "Dandenong", postcode: "3175", lga: "Greater Dandenong", zone: "outer" },
  { name: "Keysborough", postcode: "3173", lga: "Greater Dandenong", zone: "outer" },
  { name: "Endeavour Hills", postcode: "3802", lga: "Casey", zone: "outer" },
  { name: "Narre Warren", postcode: "3805", lga: "Casey", zone: "outer" },
  { name: "Berwick", postcode: "3806", lga: "Casey", zone: "outer" },
  { name: "Cranbourne", postcode: "3977", lga: "Casey", zone: "outer" },
  { name: "Hampton Park", postcode: "3976", lga: "Casey", zone: "outer" },
  { name: "Hallam", postcode: "3803", lga: "Casey", zone: "outer" },
  { name: "Carrum Downs", postcode: "3201", lga: "Frankston", zone: "outer" },
  { name: "Frankston", postcode: "3199", lga: "Frankston", zone: "outer" },
  { name: "Seaford", postcode: "3198", lga: "Frankston", zone: "outer" },
  { name: "Chelsea", postcode: "3196", lga: "Kingston", zone: "outer" },
  { name: "Carrum", postcode: "3197", lga: "Kingston", zone: "outer" },
  { name: "Warrandyte", postcode: "3113", lga: "Manningham", zone: "outer" },
  { name: "Sunbury", postcode: "3429", lga: "Hume", zone: "outer" },
  { name: "Melton", postcode: "3337", lga: "Melton", zone: "outer" },
  { name: "Melton South", postcode: "3338", lga: "Melton", zone: "outer" },
  { name: "Hoppers Crossing", postcode: "3029", lga: "Wyndham", zone: "outer" },
  { name: "Werribee", postcode: "3030", lga: "Wyndham", zone: "outer" },
  { name: "Point Cook", postcode: "3030", lga: "Wyndham", zone: "outer" },
  { name: "Tarneit", postcode: "3029", lga: "Wyndham", zone: "outer" },
  { name: "Truganina", postcode: "3029", lga: "Wyndham", zone: "outer" },
  { name: "Wyndham Vale", postcode: "3024", lga: "Wyndham", zone: "outer" },
  { name: "Williams Landing", postcode: "3027", lga: "Wyndham", zone: "outer" },
  { name: "Keilor", postcode: "3036", lga: "Brimbank", zone: "outer" },
  { name: "Taylors Lakes", postcode: "3038", lga: "Brimbank", zone: "outer" },
  { name: "Sydenham", postcode: "3037", lga: "Brimbank", zone: "outer" },
];

// Insert in batches of 30
const batchSize = 30;
for (let i = 0; i < suburbs.length; i += batchSize) {
  const batch = suburbs.slice(i, i + batchSize);
  await connection.execute(
    `INSERT IGNORE INTO suburbs (name, postcode, lga, zone, isActive) VALUES ${batch.map(() => "(?,?,?,?,1)").join(",")}`,
    batch.flatMap(s => [s.name, s.postcode, s.lga, s.zone])
  );
  console.log(`Inserted suburbs batch ${Math.floor(i/batchSize)+1}`);
}

console.log("Seed complete.");
await connection.end();
